name: Azure Data Factory CI/CD

on:
  push:
    branches:
      - AS_GITHUB_ACTIONS

jobs:
  pre-deployment:
     runs-on: ubuntu-latest
     steps:
     - name: Notify Approvers via Email
       uses: dawidd6/action-send-mail@v3
       with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{secrets.EMAIL_USERNAME}}
        password: ${{secrets.EMAIL_PASSWORD}}
        secure: false
        subject: "Approval Requiredfor Deployment"
        body : "Please approve the deploymentin Github Actions."
        to: "alokranjansah01031999@gmail.com"
        from: "alokranjansah8@gmail.com"
  approval-step:
    runs-on: ubuntu-latest
    needs: pre-deployment
    environment: ApprovalRequired
    steps:
    - name: Waiting for approval
      run: echo "Deployment waiting for approval..."
  validate:
    runs-on: [windows-latest]
    needs: approval-step
    environment: dev
    steps:
    - name: Check runner OS
      run: echo "Running on $RUNNER_OS"
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Run PowerShell script
      shell: pwsh
      env:
          OFT_AZURE_CREDENTIALS: ${{ secrets.OFT_AZURE_CREDENTIALS }}
      run: |
          Get-Location
          $datafactory_path = Join-Path -Path (Get-Location) -ChildPath "datafactory"
          write-Output $datafactory_path

          #Installing libs for adf deployment
          #Install-Module -Name Az -Repository PSGallery -Force -AllowClobber
          #Install-Module -Name azure.datafactory.tools -Scope CurrentUser

          $oft_azure_creds=$env:OFT_AZURE_CREDENTIALS
          $oft_azure_creds_json=$oft_azure_creds | ConvertFrom-Json

          $tenantId=$oft_azure_creds_json.tenantId
          $appId=$oft_azure_creds_json.clientId
          $clientKey=$oft_azure_creds_json.clientSecret
          
          $clientSecret= ConvertTo-SecureString $clientKey -AsPlainText -Force
          $credential=New-Object System.Management.Automation.PSCredential ($appId, $clientSecret)
