name: Azure Data Factory CI/CD

on:
  push:
    branches:
      - AS_GITHUB_ACTIONS

jobs:
  pre-deployment:
     runs-on: ubuntu-latest
     steps:
     - name: Install mailx
       run: sudo apt-get update && sudo apt-get install -y mailutils
     
     - name: Configure mailx SMTP settings
       run: |
         echo "set smtp=smtp://smtp.gmail.com:587" >> ~/.mailrc
         echo "set smtp-auth=login" >> ~/.mailrc
         echo "set smtp-auth-user=${{ secrets.EMAIL_USERNAME }}" >> ~/.mailrc
         echo "set smtp-auth-password=${{ secrets.EMAIL_PASSWORD }}" >> ~/.mailrc
         echo "set ssl-verify=ignore" >> ~/.mailrc
     
     - name: Send Approval Email using mailx
       run: |
         echo "Please approve the deployment in GitHub Actions." | mailx -s "Approval Required for Deployment" -r "alokranjansah8@gmail.com" "alokranjansah01031999@gmail.com"
  
  approval-step:
    runs-on: ubuntu-latest
    needs: pre-deployment
    environment: ApprovalRequired
    steps:
    - name: Waiting for approval
      run: echo "Deployment waiting for approval..."
  
  validate:
    runs-on: [windows-latest]
    needs: approval-step
    environment: dev
    steps:
    - name: Check runner OS
      run: echo "Running on $RUNNER_OS"
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Run PowerShell script
      shell: pwsh
      env:
          OFT_AZURE_CREDENTIALS: ${{ secrets.OFT_AZURE_CREDENTIALS }}
      run: |
          Get-Location
          $datafactory_path = Join-Path -Path (Get-Location) -ChildPath "datafactory"
          write-Output $datafactory_path

          #Installing libs for adf deployment
          #Install-Module -Name Az -Repository PSGallery -Force -AllowClobber
          #Install-Module -Name azure.datafactory.tools -Scope CurrentUser

          $oft_azure_creds=$env:OFT_AZURE_CREDENTIALS
          $oft_azure_creds_json=$oft_azure_creds | ConvertFrom-Json

          $tenantId=$oft_azure_creds_json.tenantId
          $appId=$oft_azure_creds_json.clientId
          $clientKey=$oft_azure_creds_json.clientSecret
          
          $clientSecret= ConvertTo-SecureString $clientKey -AsPlainText -Force
          $credential=New-Object System.Management.Automation.PSCredential ($appId, $clientSecret)
