name: Deploy App

on:
  workflow_dispatch:

run-name: Deploy triggered by ${{ github.actor }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
